//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarfieldCleaner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>alg</string>
  <string>audiodg</string>
  <string>chrome</string>
  <string>cmd</string>
  <string>conhost</string>
  <string>csrss</string>
  <string>ctfmon</string>
  <string>dllhost</string>
  <string>dwm</string>
  <string>BarfieldCleaner</string>
  <string>explorer</string>
  <string>idle</string>
  <string>lsass</string>
  <string>lsm</string>
  <string>nvvsvc</string>
  <string>rundll32</string>
  <string>regedit</string>
  <string>svchost</string>
  <string>services</string>
  <string>smss</string>
  <string>spoolsv</string>
  <string>system</string>
  <string>taskeng</string>
  <string>taskmgr</string>
  <string>vcsexpress</string>
  <string>wininit</string>
  <string>winlogon</string>
  <string>wmiprvse</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RequiredOSProcesses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RequiredOSProcesses"]));
            }
        }
    }
}
